# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sesion-6-7' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sesion-6-7
  pod 'Alamofire', '~> 5.0.0-beta.5'
  pod 'SwiftyJSON', '~> 4.0'

end
